title: Informator WMiI UJ
email: wmii@samorzad.uj.edu.pl
description: Informator studenta Wydziału Matematyki i Informatyki UJ
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://informator.ksi.ii.uj.edu.pl/"
github_username:  KSIUJ

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

navigation:
  - {file: "index.md", title: "Start"}
  - {file: "faq.md", title: "FAQ"}
  - {file: "o_informatorze.md", title: "O informatorze"}

external:
  - {title: Mail, icon: envelope, url: "mailto:wmii@samorzad.uj.edu.pl"}
  - {title: Github, icon: github, url: "https://github.com/KSIUJ/informator"}
  - {title: Edit, icon: edit, url: "https://informator.ksi.ii.uj.edu.pl/admin/"}
