title: Informator WMiI UJ
email: wmii@samorzad.uj.edu.pl
description: Informator studenta Wydziału Matematyki i Informatyki UJ
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://informator.ksi.ii.uj.edu.pl/"
github_username:  KSIUJ

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

navigation:
  - {file: "index.md", title: "Start"}
  - {file: "faq.md", title: "FAQ"}
  - {file: "o_informatorze.md", title: "O informatorze"}
