backend:
  name: github
  branch: master
  repo: KSIUJ/informator
  base_url: https://informator.ksi.ii.uj.edu.pl
  auth_endpoint: netlify-auth/auth
media_folder: 'images/uploads'
site_url: https://informator.ksi.ii.uj.edu.pl
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'pages/'
    create: true
    sortableFields: ['title']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    extension: 'md'
    format: yaml-frontmatter
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}.html"
  - name: 'core'
    label: 'Core Pages'
    label_singular: 'Core Page'
    sortableFields: ['title']
    files:
      - label: 'Index'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'fullpage' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
        preview_path: "/"
